name: Build and deploy website

on:
  push:
    branches: [ main ]
  schedule:
    # Execute this workflow:
    # Mon-Sun, every 24 hours at 6 am (UTC)
    - cron: '0 6 * * *'
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -o Acquire::Retries=5 \
                doxygen graphviz

      - name: Build website
        run: |
          cd ${{ github.workspace }}/website
          python build.py --with-doxygen

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ github.workspace }}/website/build

  # Disabled until the repo is published.
  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write  # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
